// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC08QXyIuYgbA008tDHY2zurUMJUY4MqMk',
    appId: '1:603679615508:web:16acb969bbfbaf44781501',
    messagingSenderId: '603679615508',
    projectId: 'chatchat-5e181',
    authDomain: 'chatchat-5e181.firebaseapp.com',
    storageBucket: 'chatchat-5e181.appspot.com',
    measurementId: 'G-LJ1046VQTS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAunzxUgPMksntjnT07ah3F4pC-4rSCX84',
    appId: '1:603679615508:android:7e5603a3470aebac781501',
    messagingSenderId: '603679615508',
    projectId: 'chatchat-5e181',
    storageBucket: 'chatchat-5e181.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvMGJVSiXhXUcKC0hGkYNEKyGmrL88XFY',
    appId: '1:603679615508:ios:04b19d0d0debbe71781501',
    messagingSenderId: '603679615508',
    projectId: 'chatchat-5e181',
    storageBucket: 'chatchat-5e181.appspot.com',
    iosClientId:
        '603679615508-9k955aft6b5io8260dv1r24fv09emgaf.apps.googleusercontent.com',
    iosBundleId: 'com.j.chatFunctionsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvMGJVSiXhXUcKC0hGkYNEKyGmrL88XFY',
    appId: '1:603679615508:ios:04b19d0d0debbe71781501',
    messagingSenderId: '603679615508',
    projectId: 'chatchat-5e181',
    storageBucket: 'chatchat-5e181.appspot.com',
    iosClientId:
        '603679615508-9k955aft6b5io8260dv1r24fv09emgaf.apps.googleusercontent.com',
    iosBundleId: 'com.j.chatFunctionsApp',
  );
}
